name: Generate Snake

on:
  schedule: # execute every 12 hours
    - cron: '0 */12 * * *'
    
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update snake gif
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: rvahilario
          svg_out_path: dist/github-contribution-grid-snake.svg
      - run: git status
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
